### ISSUE TITLE
Need instructions to build

### ISSUE THREAD

**Issue by AgSmith95** [sndcode/AutoClicker#1]
Hi,

It would be great to have the set of instructions on how to build this program.

Danke.

**Comment by NataliaGameDev** [comment]
Hello!
I've built this code using Windows PowerShell (Visual Studio Code) replacing the main method by:

int  main()
{
	init();
    return 0;
}

And using the command line: g++ Main.cpp -o clicker
To execute the clicker I executed the command: ./clicker

**Comment by sndcode** [comment]
@AgSmith95 @NataliaGameDev 
sorry for the ultra late answer, i never got noticed that you guys commended.
Anyways, the code is updated and the repo contains a visual studio file plus the exe files

**Comment by Harshil783** [comment]
plz close the issue if you have solved have your problems
